name: workaround w/ poetry env use VER

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: dmitry-shibanov/setup-python@v-dmshib/fix-poetry-version
      with:
        python-version: '3.10'
        cache: 'poetry'
    - run: |
        poetry install
    - run: python -V
    - run: poetry run python -V
    - run: poetry run pytest
