name: workaround w/ poetry env use VER

on: [push, workflow_dispatch]

jobs:
  build:
    name: Setup Python ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        python-version: ['pypy-3.6', 'pypy-3.7', 3.7, '3.10', '3.11.0-alpha.6']
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: dmitry-shibanov/setup-python@v-dmshib/fix-poetry-version
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - run: |
        poetry install
    - run: python -V
    - run: poetry run python -V
    - run: poetry run pytest
